/**
 * 教材メタデータ定義
 * Phase 2: 教材表示設定システム
 * 
 * 全51教材の詳細情報を管理
 */

import type { MaterialMetadata, MaterialCategory, MaterialStatus } from '../types/material';


/**
 * 全教材のメタデータ配列
 */
export const materialMetadataList: MaterialMetadata[] = [
  // 小学1年生
  {
    id: 'addition-subtraction',
    title: 'たし算・ひき算ビジュアライザー',
    description: 'リンゴを使って、たし算とひき算を楽しく学ぼう！数えながら答えを見つけてね。',
    gradeLevel: 'elementary1',
    gradeJapanese: '小学1年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['基礎', '計算', '視覚化'],
    difficulty: 'easy',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'hiragana-stroke',
    title: 'ひらがな書き順アニメーション',
    description: 'ひらがなの正しい書き順を覚えよう！アニメーションを見て、なぞり書きで練習できます。',
    gradeLevel: 'elementary1',
    gradeJapanese: '小学1年生',
    subject: 'japanese',
    subjectJapanese: '国語',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['基礎', '文字学習', 'アニメーション'],
    difficulty: 'easy',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'picture-word-matching',
    title: '絵と言葉のマッチングゲーム',
    description: '絵を見て正しい言葉を選ぼう！動物・果物・乗り物・食べ物から選べます。10問連続正解でごほうびがもらえるよ！',
    gradeLevel: 'elementary1',
    gradeJapanese: '小学1年生',
    subject: 'japanese',
    subjectJapanese: '国語',
    category: 'game',
    status: 'published',
    enabled: true,
    tags: ['語彙', 'ゲーム', '基礎'],
    difficulty: 'easy',
    estimatedTime: 10,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'clock-learning',
    title: '時計の読み方学習ツール',
    description: '時計の針をドラッグして動かしてみよう！デジタル表示と連動して、時計の読み方をマスターできます。',
    gradeLevel: 'elementary1',
    gradeJapanese: '小学1年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['時間', '基礎', 'インタラクティブ'],
    difficulty: 'easy',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'number-blocks',
    title: '数の合成・分解ブロック',
    description: '1〜10のブロックを使って数の合成・分解を学ぼう！2つ以上の数字を組み合わせて目標の数を作ってください。たくさん組み合わせると高得点！',
    gradeLevel: 'elementary1',
    gradeJapanese: '小学1年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'interactive',
    status: 'published',
    enabled: true,
    tags: ['数の構成', '基礎', 'ゲーム'],
    difficulty: 'easy',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学2年生
  {
    id: 'multiplication',
    title: 'かけ算九九の視覚化',
    description: 'アニメーションでかけ算の仕組みがよくわかる！視覚的にかけ算を理解できます。',
    gradeLevel: 'elementary2',
    gradeJapanese: '小学2年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['九九', '視覚化', '基礎'],
    difficulty: 'easy',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'unit-conversion',
    title: '長さ・かさの単位変換ツール',
    description: 'cm、m、mm、mL、dL、Lの単位変換を視覚的に学べます。スライダーで数値を変えてみよう！',
    gradeLevel: 'elementary2',
    gradeJapanese: '小学2年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['単位', '変換', '視覚化'],
    difficulty: 'easy',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'plant-growth',
    title: '植物の成長シミュレーター',
    description: '植物を育てて、成長の様子を観察しよう！水やりと日光の管理が大切です。',
    gradeLevel: 'elementary2',
    gradeJapanese: '小学2年生',
    subject: 'life',
    subjectJapanese: '生活科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['観察', 'シミュレーション', '生活'],
    difficulty: 'easy',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'town-exploration-map',
    title: '町たんけんマップ',
    description: '自分の町を探検してマップを作ろう！お店や施設を見つけて、オリジナルの地図を完成させよう。',
    gradeLevel: 'elementary2',
    gradeJapanese: '小学2年生',
    subject: 'life',
    subjectJapanese: '生活科',
    category: 'interactive',
    status: 'published',
    enabled: true,
    tags: ['地図', '探検', '生活'],
    difficulty: 'easy',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学3年生
  {
    id: 'fraction-visualization',
    title: '分数の視覚化',
    description: '分数を円グラフや棒グラフで視覚的に理解しよう！練習モードとクイズモードがあります。',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['分数', '視覚化', '基礎'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'fraction-pizza',
    title: '分数ピザカッター',
    description: 'ピザを切って分数を学ぼう！ピースをクリックして選択できます。',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'interactive',
    status: 'published',
    enabled: true,
    tags: ['分数', 'インタラクティブ', '楽しい'],
    difficulty: 'easy',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'magnet-experiment',
    title: '磁石の実験シミュレーター',
    description: '磁石の性質を体験！N極とS極の働きや、鉄・アルミ・プラスチックへの影響を観察しよう。',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['磁石', '実験', 'シミュレーション'],
    difficulty: 'easy',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'fraction-master',
    title: '分数マスターツール',
    description: '分数の概念を総合的に学習！視覚化、計算、約分まで段階的に理解できます。',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['分数', '10歳の壁', '重要'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-06T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'material',
  },
  {
    id: 'insect-metamorphosis',
    title: '昆虫の変態シミュレーター',
    description: '昆虫の成長過程を観察！完全変態と不完全変態の違いを学ぼう。',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['昆虫', '成長', '観察'],
    difficulty: 'easy',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'compass-simulator',
    title: '方位磁針シミュレーター',
    description: '方位磁針の使い方を学ぼう！東西南北の方角を確認できます。',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'social',
    subjectJapanese: '社会',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['方位', '地図', '基礎'],
    difficulty: 'easy',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学4年生
  {
    id: 'area-calculator',
    title: '面積計算ツール',
    description: '図形の頂点をドラッグして面積を計算！正方形、長方形、三角形、平行四辺形の面積を視覚的に学べます。',
    gradeLevel: 'elementary4',
    gradeJapanese: '小学4年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['面積', '図形', 'インタラクティブ'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'water-state',
    title: '水の三態変化アニメーション',
    description: '温度による水の状態変化を観察！氷・水・水蒸気の分子の動きをアニメーションで学習できます。',
    gradeLevel: 'elementary4',
    gradeJapanese: '小学4年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['状態変化', 'アニメーション', '分子'],
    difficulty: 'normal',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'electric-circuit',
    title: '電気回路シミュレーター',
    description: '電池、豆電球、スイッチを使って電気回路を作ろう！直列回路と並列回路の違いを学べます。',
    gradeLevel: 'elementary4',
    gradeJapanese: '小学4年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['電気', '回路', 'シミュレーション'],
    difficulty: 'normal',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'abstract-thinking-bridge',
    title: '抽象的思考への橋',
    description: '10歳の壁を乗り越える！具体的な操作から抽象的な理解へ段階的に導きます。',
    gradeLevel: 'elementary4',
    gradeJapanese: '小学4年生',
    subject: 'math',
    subjectJapanese: '総合',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['10歳の壁', '抽象思考', '重要'],
    difficulty: 'normal',
    estimatedTime: 45,
    isPremium: false,
    createdAt: '2025-06-06T00:00:00.000Z',
    updatedAt: '2025-06-06T00:00:00.000Z',
    moduleType: 'material',
  },
  {
    id: 'angle-measurement',
    title: '角度測定器',
    description: '分度器の使い方をマスター！角度を測ったり、指定された角度を作ったりできます。',
    gradeLevel: 'elementary4',
    gradeJapanese: '小学4年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['角度', '測定', 'ツール'],
    difficulty: 'normal',
    estimatedTime: 15,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'prefecture-puzzle',
    title: '都道府県パズル',
    description: '日本の都道府県を楽しく覚えよう！パズル形式で位置と名前を学習できます。',
    gradeLevel: 'elementary4',
    gradeJapanese: '小学4年生',
    subject: 'social',
    subjectJapanese: '社会',
    category: 'game',
    status: 'published',
    enabled: true,
    tags: ['地理', 'パズル', '都道府県'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学5年生
  {
    id: 'speed-time-distance',
    title: '速さ・時間・距離の関係シミュレーター',
    description: '物体の移動をアニメーションで確認！速さ・時間・距離の関係を視覚的に理解できます。',
    gradeLevel: 'elementary5',
    gradeJapanese: '小学5年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['速さ', 'アニメーション', '応用'],
    difficulty: 'normal',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'pendulum-experiment',
    title: '振り子の実験装置',
    description: '振り子の長さと重さを調整して周期を測定！実験データをグラフ化して法則を発見しよう。',
    gradeLevel: 'elementary5',
    gradeJapanese: '小学5年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['振り子', '実験', 'データ分析'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'weather-change-simulator',
    title: '天気の変化シミュレーター',
    description: '雲の動きと天気の変化を観察！気圧配置から天気を予測してみよう。',
    gradeLevel: 'elementary5',
    gradeJapanese: '小学5年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['天気', '気象', 'シミュレーション'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'industrial-zone-map',
    title: '工業地帯マップ',
    description: '日本の主な工業地帯を学習！各地域の特色ある工業を地図で確認できます。',
    gradeLevel: 'elementary5',
    gradeJapanese: '小学5年生',
    subject: 'social',
    subjectJapanese: '社会',
    category: 'interactive',
    status: 'published',
    enabled: true,
    tags: ['工業', '地理', '経済'],
    difficulty: 'normal',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学6年生
  {
    id: 'proportion-graph',
    title: '比例・反比例グラフツール',
    description: 'リアルタイムでグラフを描画！比例・反比例の関係を視覚的に理解できます。',
    gradeLevel: 'elementary6',
    gradeJapanese: '小学6年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['比例', 'グラフ', '関数'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'lever-principle',
    title: 'てこの原理実験器',
    description: '支点・力点・作用点を調整してつり合いを作ろう！てこの原理を実験で確認できます。',
    gradeLevel: 'elementary6',
    gradeJapanese: '小学6年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['てこ', '物理', '実験'],
    difficulty: 'normal',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'combination-simulator',
    title: '場合の数シミュレーター',
    description: '組み合わせや並び方を視覚的に理解！樹形図で場合の数を数えられます。',
    gradeLevel: 'elementary6',
    gradeJapanese: '小学6年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['組み合わせ', '確率', '樹形図'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'human-body-animation',
    title: '人体の仕組みアニメーション',
    description: '消化器系・循環器系・呼吸器系の働きをアニメーションで学習！',
    gradeLevel: 'elementary6',
    gradeJapanese: '小学6年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['人体', 'アニメーション', '生物'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 中学1年生
  {
    id: 'number-line',
    title: '正負の数の数直線',
    description: '数直線を使って、マイナスの数も理解しよう！正負の数の計算をマスターできます。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['正負の数', '数直線', '基礎'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'algebraic-expression',
    title: '文字式変形ツール',
    description: '文字式の展開、因数分解、同類項の整理をステップごとに学習！計算過程が見える化されます。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['文字式', '代数', '基礎'],
    difficulty: 'normal',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'light-refraction',
    title: '光の屈折実験器',
    description: '光の屈折現象を観察しよう！入射角を変えて、スネルの法則を確認できます。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['光', '屈折', '物理'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'moving-point-p',
    title: '動く点P - 三角形の面積変化',
    description: '四角形上を移動する点Pが作る三角形の面積変化を観察！関数の考え方を視覚的に学習。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'interactive',
    status: 'published',
    enabled: true,
    tags: ['関数', '面積', '動的'],
    difficulty: 'hard',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-04T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'english-speaking-practice',
    title: '英語スピーキング練習システム',
    description: '実践的な英会話を段階的に学習！AIアシスタントとの対話で自信をつけよう。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'english',
    subjectJapanese: '英語',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['英会話', 'スピーキング', '重要'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-06T00:00:00.000Z',
    updatedAt: '2025-06-06T00:00:00.000Z',
    moduleType: 'material',
  },
  {
    id: 'pronunciation-practice',
    title: '発音練習ツール',
    description: '音素レベルから正しい英語の発音を学習！ネイティブ音声と比較しながら練習できます。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'english',
    subjectJapanese: '英語',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['発音', '音素', '基礎'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-06T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'material',
  },
  {
    id: 'algebra-introduction',
    title: '代数入門システム',
    description: '算数から数学への架け橋！文字を使った式の考え方を段階的に学習できます。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['代数', '文字式', '重要'],
    difficulty: 'normal',
    estimatedTime: 35,
    isPremium: false,
    createdAt: '2025-06-06T00:00:00.000Z',
    updatedAt: '2025-06-06T00:00:00.000Z',
    moduleType: 'material',
  },
  {
    id: 'earthquake-wave-simulator',
    title: '地震波シミュレーター',
    description: 'P波とS波の違いを視覚的に理解！地震計の記録も確認できます。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['地震', '波', 'シミュレーション'],
    difficulty: 'normal',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-08T00:00:00.000Z',
    updatedAt: '2025-06-08T00:00:00.000Z',
    moduleType: 'material',
  },
  {
    id: 'time-zone-calculator',
    title: '時差計算ツール',
    description: '世界の主要都市の時差を計算！日付変更線の仕組みも学べます。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'social',
    subjectJapanese: '社会',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['時差', '地理', '国際'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-08T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'material',
  },
  
  // 中学2年生
  {
    id: 'linear-function',
    title: '一次関数グラフ描画ツール',
    description: '一次関数y=ax+bのグラフを自在に操作！傾きと切片を調整して、グラフの変化を観察しよう。',
    gradeLevel: 'juniorHigh2',
    gradeJapanese: '中学2年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['一次関数', 'グラフ', '関数'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'atom-molecule',
    title: '原子・分子構造シミュレーション',
    description: '分子の3D構造を観察！電子軌道のアニメーションで化学結合を理解しよう。',
    gradeLevel: 'juniorHigh2',
    gradeJapanese: '中学2年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['化学', '分子', '3D'],
    difficulty: 'normal',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'chemical-reaction',
    title: '化学反応シミュレーター',
    description: '化学反応を分子レベルで観察！質量保存の法則を視覚的に確認できます。',
    gradeLevel: 'juniorHigh2',
    gradeJapanese: '中学2年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['化学反応', '質量保存', 'シミュレーション'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'element-puzzle',
    title: '元素記号パズルゲーム',
    description: 'パズルゲームで元素記号を覚えよう！連鎖を作って高得点を目指せ！',
    gradeLevel: 'juniorHigh2',
    gradeJapanese: '中学2年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'game',
    status: 'published',
    enabled: true,
    tags: ['元素', 'ゲーム', '暗記'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-04T00:00:00.000Z',
    updatedAt: '2025-06-04T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'proof-step-builder',
    title: '証明ステップビルダー',
    description: '論理的思考力を鍛える！図形の証明を段階的に組み立てよう。',
    gradeLevel: 'juniorHigh2',
    gradeJapanese: '中学2年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['証明', '論理', '図形'],
    difficulty: 'hard',
    estimatedTime: 40,
    isPremium: false,
    createdAt: '2025-06-08T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'material',
  },
  {
    id: 'electricity-experiment',
    title: '電流・電圧・抵抗の関係実験器',
    description: 'オームの法則を実験で確認！回路を自由に組み立てて測定できます。',
    gradeLevel: 'juniorHigh2',
    gradeJapanese: '中学2年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['電気', 'オームの法則', '実験'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-08T00:00:00.000Z',
    updatedAt: '2025-06-08T00:00:00.000Z',
    moduleType: 'material',
  },
  
  // 中学3年生
  {
    id: 'sorting-algorithm',
    title: 'ソートアルゴリズム可視化',
    description: '様々なソートアルゴリズムの動きを視覚的に理解！効率の違いを比較しよう。',
    gradeLevel: 'juniorHigh3',
    gradeJapanese: '中学3年生',
    subject: 'math',
    subjectJapanese: '情報',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['アルゴリズム', 'プログラミング', '情報'],
    difficulty: 'hard',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'inertia-simulation',
    title: '慣性の法則シミュレーション',
    description: '電車内での慣性現象を体験！急発進・急停止時の動きを観察しよう。',
    gradeLevel: 'juniorHigh3',
    gradeJapanese: '中学3年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['物理', '慣性', 'シミュレーション'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-04T00:00:00.000Z',
    updatedAt: '2025-06-04T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'quadratic-function',
    title: '二次関数グラフ変形ツール',
    description: '二次関数のグラフを自在に操作！頂点や軸の移動を視覚的に理解できます。',
    gradeLevel: 'juniorHigh3',
    gradeJapanese: '中学3年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['二次関数', 'グラフ', '放物線'],
    difficulty: 'hard',
    estimatedTime: 25,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'celestial-motion',
    title: '天体の動きシミュレーター',
    description: '惑星の動きを3Dで観察！日食・月食の仕組みも理解できます。',
    gradeLevel: 'juniorHigh3',
    gradeJapanese: '中学3年生',
    subject: 'science',
    subjectJapanese: '理科',
    category: 'simulation',
    status: 'published',
    enabled: true,
    tags: ['天体', '3D', '宇宙'],
    difficulty: 'hard',
    estimatedTime: 35,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 高校1年生
  {
    id: 'function-graph',
    title: '関数グラフ動的描画ツール',
    description: '様々な関数のグラフをリアルタイムで描画！パラメータを調整して変化を観察しよう。',
    gradeLevel: 'highSchool1',
    gradeJapanese: '高校1年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['関数', 'グラフ', '動的'],
    difficulty: 'hard',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2024-12-01T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'typing-puyo',
    title: 'ぷよぷよ風タイピングゲーム',
    description: 'タイピング練習をゲームで楽しく！連鎖を作って高得点を目指そう。',
    gradeLevel: 'highSchool1',
    gradeJapanese: '高校1年生',
    subject: 'math',
    subjectJapanese: '情報',
    category: 'game',
    status: 'published',
    enabled: true,
    tags: ['タイピング', 'ゲーム', 'スキル'],
    difficulty: 'normal',
    estimatedTime: 20,
    isPremium: false,
    createdAt: '2025-06-04T00:00:00.000Z',
    updatedAt: '2025-06-19T10:00:00.000Z',
    moduleType: 'component',
  },
  {
    id: 'trigonometric-function',
    title: '三角関数グラフ描画ツール',
    description: '三角関数のグラフを動的に描画！振幅・周期・位相の変化を観察できます。',
    gradeLevel: 'highSchool1',
    gradeJapanese: '高校1年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['三角関数', 'グラフ', '周期'],
    difficulty: 'hard',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 高校2年生
  {
    id: 'calculus-visualizer',
    title: '微分積分ビジュアライザー',
    description: '微分と積分の概念を視覚的に理解！接線や面積の変化をアニメーションで確認。',
    gradeLevel: 'highSchool2',
    gradeJapanese: '高校2年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'visualization',
    status: 'published',
    enabled: true,
    tags: ['微分', '積分', '解析'],
    difficulty: 'hard',
    estimatedTime: 40,
    isPremium: false,
    createdAt: '2025-06-05T00:00:00.000Z',
    updatedAt: '2025-06-05T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学3年生（追加教材）
  {
    id: 'decimal-master',
    title: '小数マスター',
    description: '視覚的に小数を理解！0.1と0.01の概念から計算まで、段階的に学習できます。',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['小数', '位取り', '計算', '視覚的学習'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-21T00:00:00.000Z',
    updatedAt: '2025-06-21T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学5年生（追加教材）
  {
    id: 'percentage-trainer',
    title: '割合・百分率トレーナー',
    description: '割合の概念から実生活での応用まで！円グラフや買い物計算で楽しく学習。',
    gradeLevel: 'elementary5',
    gradeJapanese: '小学5年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['割合', '百分率', 'パーセント', 'グラフ', '実生活応用'],
    difficulty: 'normal',
    estimatedTime: 35,
    isPremium: false,
    createdAt: '2025-06-21T00:00:00.000Z',
    updatedAt: '2025-06-21T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 中学1年生（追加教材）
  {
    id: 'equation-builder',
    title: '一次方程式ビルダー',
    description: '天秤のメタファーで等式の性質を理解！段階的に一次方程式の解法をマスター。文章題から式を作る力も育成。',
    gradeLevel: 'juniorHigh1',
    gradeJapanese: '中学1年生',
    subject: 'math',
    subjectJapanese: '数学',
    category: 'tool',
    status: 'published',
    enabled: true,
    tags: ['方程式', '移項', '等式の性質', '文章題', '天秤'],
    difficulty: 'normal',
    estimatedTime: 40,
    isPremium: false,
    createdAt: '2025-06-21T00:00:00.000Z',
    updatedAt: '2025-06-21T00:00:00.000Z',
    moduleType: 'component',
  },
  
  // 小学3年生（分数計算トレーナー）
  {
    id: 'fraction-trainer',
    title: '分数計算トレーナー',
    description: '小学3年生〜中学生向けの包括的な分数学習教材。視覚的理解から実生活応用まで、10段階の学習モードで段階的に分数をマスター！',
    gradeLevel: 'elementary3',
    gradeJapanese: '小学3年生',
    subject: 'math',
    subjectJapanese: '算数',
    category: 'practice',
    status: 'published',
    enabled: true,
    tags: ['分数', '計算', '視覚化', '実生活', '約分', '通分', '帯分数'],
    difficulty: 'normal',
    estimatedTime: 30,
    isPremium: false,
    createdAt: '2025-06-21T00:00:00.000Z',
    updatedAt: '2025-06-21T00:00:00.000Z',
    moduleType: 'component',
  }
];

/**
 * IDから教材メタデータを取得
 */
export const getMaterialById = (id: string): MaterialMetadata | undefined => {
  return materialMetadataList.find(material => material.id === id);
};

/**
 * 学年で教材をフィルタリング
 */
export const getMaterialsByGrade = (grade: string): MaterialMetadata[] => {
  return materialMetadataList.filter(material => material.gradeJapanese === grade);
};

/**
 * 教科で教材をフィルタリング
 */
export const getMaterialsBySubject = (subject: string): MaterialMetadata[] => {
  return materialMetadataList.filter(material => material.subjectJapanese === subject);
};

/**
 * ステータスで教材をフィルタリング
 */
export const getMaterialsByStatus = (status: MaterialStatus): MaterialMetadata[] => {
  return materialMetadataList.filter(material => material.status === status);
};

/**
 * 有効な教材のみを取得
 */
export const getEnabledMaterials = (): MaterialMetadata[] => {
  return materialMetadataList.filter(material => material.enabled);
};

/**
 * 教材統計情報を生成
 */
export const generateMaterialStatistics = (): {
  total: number;
  byGrade: Record<string, number>;
  bySubject: Record<string, number>;
  byStatus: Record<MaterialStatus, number>;
  byCategory: Record<MaterialCategory, number>;
  enabled: number;
} => {
  const stats = {
    total: materialMetadataList.length,
    byGrade: {} as Record<string, number>,
    bySubject: {} as Record<string, number>,
    byStatus: {
      development: 0,
      testing: 0,
      published: 0,
    },
    byCategory: {
      visualization: 0,
      simulation: 0,
      game: 0,
      practice: 0,
      interactive: 0,
      tool: 0,
    },
    enabled: 0,
  };

  materialMetadataList.forEach(material => {
    // 学年別
    stats.byGrade[material.gradeJapanese] = (stats.byGrade[material.gradeJapanese] || 0) + 1;
    
    // 教科別
    stats.bySubject[material.subjectJapanese] = (stats.bySubject[material.subjectJapanese] || 0) + 1;
    
    // ステータス別
    stats.byStatus[material.status]++;
    
    // カテゴリー別
    stats.byCategory[material.category]++;
    
    // 有効数
    if (material.enabled) stats.enabled++;
  });

  return stats;
};